In [1]:
import numpy as np

In [9]:
racing_line_points = np.load("Canada_Training-1000-4-2019-10-11-163418.npy")

In [12]:
racing_line_points

array([[ 4.58690814,  1.62381599],
       [ 4.48738106,  1.65427416],
       [ 4.38725046,  1.68433614],
       [ 4.28650273,  1.71406729],
       [ 4.18493776,  1.74356116],
       [ 4.08163985,  1.77406108],
       [ 3.97832333,  1.80508233],
       [ 3.87512443,  1.83662263],
       [ 3.77211047,  1.86872584],
       [ 3.66931665,  1.90142676],
       [ 3.5667727 ,  1.93477735],
       [ 3.46450369,  1.96882859],
       [ 3.36251967,  2.00359792],
       [ 3.26080706,  2.03904586],
       [ 3.15932308,  2.07506231],
       [ 3.05802492,  2.11153893],
       [ 2.95687354,  2.14837789],
       [ 2.85585551,  2.18554509],
       [ 2.75883824,  2.22060616],
       [ 2.66230625,  2.25419253],
       [ 2.56644797,  2.28554876],
       [ 2.47140549,  2.31398797],
       [ 2.37731947,  2.33884628],
       [ 2.28436053,  2.35948844],
       [ 2.19273576,  2.37537617],
       [ 2.10270351,  2.38604352],
       [ 2.01457372,  2.39108769],
       [ 1.92870117,  2.39017183],
       [ 1.8455711 ,

In [19]:
node = np.array([4.58690814,  1.62381599])
def closest_node(node, nodes):
    # I think this gets a list of vectors. The vector from the points in the list to my point.
    # One of them (The closest) will have the lowest value
    # Math!
    deltas = nodes - node
    # This here is matrix math... I will just use it for now, and understand it later
    # http://ajcr.net/Basic-guide-to-einsum/
    # https://stackoverflow.com/questions/26089893/understanding-numpys-einsum
    # It's quick, according to : https://codereview.stackexchange.com/questions/28207/finding-the-closest-point-to-a-list-of-points
    # It's a 'dot product' thing. It gets the closest element from the array...
    dist_2 = np.einsum('ij,ij->i', deltas, deltas)
    return np.argmin(dist_2)

closest_node(node, racing_line_points)

0

In [197]:
nodes = np.array([[ 1,  1],
                  [ 2,  1],
                  [ 2,  2],
                  [ 1,  2]])
nodes
nodes2 = np.array([[ 2,  1],
                   [ 3,  1],
                   [ 4,  2],
                   [ 4,  3],
                   [ 3,  4],
                   [ 2,  4],
                   [ 1,  3],
                   [ 1,  2]])
nodes2[0]

array([2, 1])

In [203]:
node = np.array([2, 1])
#closest_node(node, nodes)
deltas = nodes2 - node
dist_2 = np.einsum('ij,ij->i', deltas, deltas)
points_pos = np.argsort(dist_2)[:2]
print("CLosest are index {} and index {}".format(points_pos[0],points_pos[1]))
points = np.array([nodes2[points_pos[0]],nodes2[points_pos[1]]])
points


CLosest are index 0 and index 1


array([[2, 1],
       [3, 1]])

In [204]:
path = nodes2
closest_2_nodes = points
print("Points: {}".format(points))
closest_point = path[points_pos[0]]
previous_point = path[points_pos[0] - 1]
#print(path.shape[0])
print(points_pos[0])
if points_pos[0] == path.shape[0] - 1:
    next_point = path[0]
else:
    next_point = path[points_pos[0] + 1]
    
print("Prev - {}".format(previous_point))
print("Closest - {}".format(closest_point))
print("Next - {}".format(next_point))

Points: [[2 1]
 [3 1]]
0
Prev - [1 2]
Closest - [2 1]
Next - [3 1]


In [205]:
angle_both = math.degrees(math.atan2(next_point[1] - previous_point[1], next_point[0] - previous_point[0]))
print("Deltay: {} - Deltax: {}".format(next_point[1] - previous_point[1], next_point[0] - previous_point[0]))
angle1 = math.degrees(math.atan2(closest_point[1] - previous_point[1], closest_point[0] - previous_point[0]))
print("Deltay: {} - Deltax: {}".format(closest_point[1] - previous_point[1], closest_point[0] - previous_point[0]))
angle2 = math.degrees(math.atan2(next_point[1] - closest_point[1], next_point[0] - closest_point[0]))
print("Deltay: {} - Deltax: {}".format(next_point[1] - closest_point[1], next_point[0] - closest_point[0]))
    
print("Angle_both: {}\nAngle1: {}\nAngle2: {}".format(angle_both,angle1, angle2))

Deltay: -1 - Deltax: 2
Deltay: -1 - Deltax: 1
Deltay: 0 - Deltax: 1
Angle_both: -26.56505117707799
Angle1: -45.0
Angle2: 0.0


In [149]:
math.degrees(math.atan2(points[0][0]-points[1][0],points[0][1]-points[1][1]))

45.0

In [135]:
l0 = nodes[0] 
l1 = nodes[2]
p1 = node
np.linalg.norm(np.cross(l1-l0, l0-p1))/np.linalg.norm(l1-l0)

0.7071067811865475

In [213]:
a = 1
b = 0.08
x = 1
y = pow(a * (1-b),x)
y

0.92

In [239]:
a = 0.9
w = 0.1
fac = 0.1

(1 - (w * (1 - fac)))

0.91

In [240]:
a = 2
a *= 2

In [241]:
a

4

In [243]:
1e-03

0.001